POST https://i.mly.app/reply
Content-Type: application/json;charset=UTF-8
Api-Key: aaa
Api-Secret: aaa

{
  "content": "",
  "type": 2,
  "from": 225,
  "fromName": "Test",
  "to": 225,
  "toName": "Test"
}

###
